### ISSUE TITLE
Form submissions need adjusting

### ISSUE THREAD

**Issue by brashrebel** [realbig/RBM_TH_LMWW2#3]
When someone does something on Larry's site, not sure if it is a comment or a form submission or something, it comes in as from Real Big Websites and goes to his spam. It needs to be more useful for him.

**Comment by brashrebel** [comment]
Looks like it is the Gravity Forms.

**Comment by d4mation** [comment]
That's weird that that's happening.

I've looked into this and the only form on the site seems to be generating its `FROM:` Header using data entered into the Form.

However, none of those Fields are required, so maybe Users aren't filling out their own name and e-mail address so it then defaults to Real Big Websites?

**Comment by d4mation** [comment]
Looking at the forwarded e-mail you just sent me, in that case it did have that information filled out.

I'll look into this more.

**Comment by d4mation** [comment]
Looks to be related to realbig/rbw-functionality#3 at [this comment](https://github.com/realbig/rbw-functionality/issues/3#issuecomment-189018730). Ultimate Branding is [likely overwriting the settings that Gravity Forms is setting](https://www.gravityhelp.com/forums/topic/from-name-and-sender-in-wpmu#post-83983).

It seems that we _should_ be able to just deactivate Ultimate Branding as the desired functionality has been moved out into our own plugins. Reading through that Gravity Help post makes me believe it is doing us way more harm than good. The E-Mail From functionality isn't worth keeping it enabled I don't think.

**Comment by brashrebel** [comment]
Let's give it a shot.

**Comment by d4mation** [comment]
Ultimate Branding has been deactivated. I'll fill out the form real quick on the site to see if it makes it to him properly.

**Comment by d4mation** [comment]
Just heard back. The email ended up in his regular inbox and he says there are no RealBigWebsites emails in his spam anymore.
